### ISSUE TITLE
Update the Wiki's explanation of goal modeling 

### ISSUE THREAD

**Issue by Noel-Bastubbe** [Noel-Bastubbe/for-Construction-Modeling#106]
## User stories
As a user I want a comprehensable explanation of how to model goals in for-Construction-Modeling in order to do it myself.

## Acceptance Criteria
- [x] [The general wiki page for goal modeling](https://github.com/Noel-Bastubbe/for-Construction-Modeling/wiki/Goal-Modeling-in-for-Construction-Modeling) is updated

**Comment by rebekka0111** [comment]
links to the objective modeler and dependency modeler must be added

**Comment by Firsttryy** [comment]
> links to the objective modeler and dependency modeler must be added

Done
