### ISSUE TITLE
[PS] add Action Behavior for Duration of 0

### ISSUE THREAD

**Issue by Firsttryy** [Noel-Bastubbe/for-Construction-Modeling#185]
## User stories
As a User I want Tasks without duration or Duration of 0 to have the correct start and end time in order to plan my tasks correctly.

## Acceptance Criteria
- [x] start method checks for duration-0-activities and returns according new State (no Objects get blocked, but old Objects get new State, Action is never running but instantaneously in history)

**Comment by Noel-Bastubbe** [comment]
How do we represent an instant activity in the excel sheet?
