### ISSUE TITLE
Update architecture in Wiki

### ISSUE THREAD

**Issue by simonmichaelnowack** [Noel-Bastubbe/for-Construction-Modeling#58]
## User stories
As a developer I want to have an overview of the architecture of for-Construction-Modeling in order to have a better understanding.

## Acceptance Criteria
- [x] image of architecture in Wiki contains Objective and Dependency Modeler 
- [x] Dependency and Objective Modeler are linked to mediator
- [x] Dependency and Objective Modeler have link (like Data Modeler for example) to their source

**Comment by Franka-T** [comment]
Should we link the termination condition modeler as a source for the dependency modeler?
